USE [Pruebas]
GO

/****** Object:  Table [dbo].[City]    Script Date: 07/07/2023 02:56:04 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[City](
	[CODE] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPTION] [varchar](50) NULL,
 CONSTRAINT [PK__City__AA1D437804095DB6] PRIMARY KEY CLUSTERED 
(
	[CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

