USE [Pruebas]
GO

/****** Object:  Table [dbo].[Seller]    Script Date: 07/07/2023 02:56:20 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Seller](
	[CODE] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](50) NULL,
	[LAST_NAME] [varchar](50) NULL,
	[DOCUMENT] [varchar](50) NULL,
	[CITY_ID] [int] NULL,
 CONSTRAINT [PK__Seller__AA1D4378DF1AF919] PRIMARY KEY CLUSTERED 
(
	[CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[Seller]  WITH CHECK ADD  CONSTRAINT [FK__Seller__CITY_ID__4BAC3F29] FOREIGN KEY([CITY_ID])
REFERENCES [dbo].[City] ([CODE])
GO

ALTER TABLE [dbo].[Seller] CHECK CONSTRAINT [FK__Seller__CITY_ID__4BAC3F29]
GO

